name: ArcaneLog
version: @version@
author: SimonOrJ
description: Arcane Logging
main: com.arcaneminecraft.log.ArcaneLog
website: https://arcaneminecraft.com/
api-version: 1.13

depend: [ArcaneAPI]
softdepend: [CoreProtect]
