name: ArcaneModeration
version: 2.0.0-SNAPSHOT
authors: [Agentred100, jugglingman456, SimonOrJ]
description: Arcane Moderation Plugin
main: com.arcaneminecraft.moderation.ArcaneModeration
website: https://arcaneminecraft.com/

depend: [ArcaneSurvival]

commands:
  alert:
    description: Modify types of alerts received
    usage: /alert
    permission: arcane.mod
  opme:
    description: Ops the command-running layer
    permission: arcane.op
  g0:
    aliases: [g1, g2, g3, gsurvival, gcreative, gadventure, gspectator]
    description: Admin command; change gamemode
    usage: /g<gamemode>
    permission: arcane.op

permissions:
  arcane.op: # DANGEROUS PERMISSION: do NOT give this to common players
    default: op
  arcane.alert.op:
    default: op
  arcane.alert.receive: # command alerts will not flood into console
    default: op
    children:
      arcane.alert.receive.command.all: true
      arcane.alert.receive.command.suspicious: true
      arcane.alert.receive.antixray: true
  arcane.alert.receive.command.all: # Receive all command alerts
    default: op
    children:
      arcane.alert.receive.command.suspicious: true
  arcane.alert.receive.command.suspicious: # Receive suspicious command alerts
    default: op
  arcane.alert.receive.antixray: # Receive diamond alerts
    default: op
  arcane.alert.ignore.command.common: # Ignore this player's common command usage
    default: op
