name: ArcaneLog
version: ${project.version}
authors: [Agentred100, jugglingman456, SimonOrJ]
description: Arcane Logging
main: com.arcaneminecraft.log.ArcaneLog
website: https://arcaneminecraft.com/

depend: [ArcaneAPI]
softdepend: [CoreProtect]
